# -*- coding: utf-8 -*-
"""reconocimiento de huellas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zB1Y1K31visTnPiro4Jf2sgf0W7fChwI
"""

## subimos archivo zip con las imagenes
from google.colab import files
uploaded = files.upload()

## leemos el arvhico y extraemos la imagenes
import zipfile
import os

zip_path = "Huellas.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("dataset")

print("Archivos extraídos correctamente")

import cv2
import os
import random
import time

## datos
DATASET_PATH = "dataset"
# umbral
RATIO = 0.75

## leemos y convertimos imagenes
def preprocess_image(path):
    img = cv2.imread(path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ## convertimos la imagen en binario
    binary = cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY_INV,11,2)
    ## retornaos la imagen en binario
    return binary


## procesamos la imagen y extraemos datos ORB
def extract_features(image):
    orb = cv2.ORB_create(nfeatures=1500)
    keypoints, descriptors = orb.detectAndCompute(image, None)
    return keypoints, descriptors

## almacenamos mejores emparejamientos
def match_features(desc1, desc2):
    bf = cv2.BFMatcher(cv2.NORM_HAMMING)
    matches = bf.knnMatch(desc1, desc2, k=2)

    good_matches = []

    for m, n in matches:
        if m.distance < RATIO * n.distance:
            good_matches.append(m)

    return len(good_matches)

## realizamos busqueda y emparejamiento de la imagen mas acertada
def main():

    ## inicializamos tiempo
    start_time = time.time()

    ## recorremos imagenes
    images = [f for f in os.listdir(DATASET_PATH) if f.lower().endswith(".tif")]

    # seleccionamos una aleatoria
    imagenAleatoria = random.choice(images)
    pertenece = imagenAleatoria.split("_")[0]

    ## mostramos la aleatoria y a que clase pertecene
    print("Huella seleccionada (desconocida):", imagenAleatoria)
    print("Clase real:", pertenece)

    ## procesamos datos de la huella aleatoria
    unknown_path = os.path.join(DATASET_PATH, imagenAleatoria)
    unknown_processed = preprocess_image(unknown_path)
    _, unknown_desc = extract_features(unknown_processed)

    ## inicializamos variables
    best_score = 0
    predicted_class = None
    best_match_image = None

    # realizamos busqueda
    for img_name in images:

        ## si es la misma que continue con el ciclo
        if img_name == imagenAleatoria:
            continue

        ## procesamos imagen entrante
        img_path = os.path.join(DATASET_PATH, img_name)

        processed = preprocess_image(img_path)
        _, desc = extract_features(processed)

        if unknown_desc is None or desc is None:
            continue

        score = match_features(unknown_desc, desc)

        img_class = img_name.split("_")[0]

        # ver la mas parecida
        if score > best_score:
            best_score = score
            predicted_class = img_class
            best_match_image = img_name

    end_time = time.time()

    # Mostrar mensaje
    print("\n===== RESULTADOS =====")
    print("Clase predicha:", predicted_class)
    print("Imagen con mayor coincidencia:", best_match_image)
    print("Puntaje de coincidencia:", best_score)
    print("Tiempo de ejecución: {:.4f} segundos".format(end_time - start_time))

main()

"""**¿Por qué una huella podría dar un puntaje bajo a pesar de ser del mismo
usuario?**

R// Esto puede ser debido a los puntos en los cuales fueron tomadas las fotos de las huellas, ya que un angulo disntinto puede enfocar en gran medida algunos detalles de una huella, lo cual hace que al convertir los datos en binarios, su información sea distinta ya que se esta obteniendo una leve información menos, no coincida lo suficiente con los datos de la otra imagen.

**¿Cómo escalaría este sistema si en lugar de 80 imágenes tuviera 80,000
(énfasis en computación en la nube)?**

R// El sistema escalaria en unas medidas de mejor manera, y en otras si dificultaria. De la forma que dificultaria seria a la hora de procesar las 80.000 imagenes y comparar la que se tomo aleatoria con las otras 79.999, se demoraria bastante tiempo de mas ejecutandose con más imagenes, entre más imagenes más lento. En la manera que lo mejoraria seria en la precision del resultado, daria un resultado más preciso y con más facilidad identificaria la clase a la que pertenece la huella
"""